{% set python_min = "3.10" %}
{% set name = "climix" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/climix-{{ version }}.tar.gz
  sha256: 2178a4410598de2080f4413cd15c2ca6d42eedef00a15357dc8de79877dd4b3e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - climix = climix.main:main
    - climix-index-docs = climix.index_docs:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - cftime
    - cf-units
    - dask >=2023.1.0
    - gordias
    - isodate
    - numba
    - numpy <2
    - pyxdg
    - pyyaml
    - regex
    - iris >=3,<4
    - sparse

test:
  imports:
    - climix
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check
    - climix --help
    - pytest --ignore-glob=**/integration/*

about:
  home: https://git.smhi.se/climix/climix
  summary: A climate index package
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://git.smhi.se/climix/climix
  doc_url: https://climix.readthedocs.io

extra:
  recipe-maintainers:
    - nCarolina
    - ljoakim
    - zklaus
